# Generated by Django 3.0.4 on 2020-04-02 10:43

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0002_auto_20200401_1459'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='post',
            new_name='Post02',
        ),
    ]
